services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - db
    restart: unless-stopped

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel
    restart: unless-stopped

volumes:
  dbdata:

networks:
  laravel:
